INSERT INTO CARRIER (carrierid, NAME)
VALUES (3848, 'JB Hunt FTL');

INSERT INTO CARRIER (carrierid, NAME)
VALUES (6006, 'Amazon');

INSERT INTO TRUCKLOAD(ID, SOURCE, DESTINATION, CARRIERID)
VALUES (1, 'Bentonville', 'Fayetteville', 3848);

INSERT INTO TRUCKLOAD(ID, SOURCE, DESTINATION, CARRIERID)
VALUES (2, 'Bentonville', 'Rogers', 3848);

INSERT INTO TRUCKLOAD(ID, SOURCE, DESTINATION, CARRIERID)
VALUES (3, 'Bentonville', 'Fayetteville', 3848);

INSERT INTO TRUCKLOAD(ID, SOURCE, DESTINATION, CARRIERID)
VALUES (4, 'Bentonville', 'ROGERS', 6006);

INSERT INTO TRUCKLOAD(ID, SOURCE, DESTINATION, CARRIERID)
VALUES (5, 'Little Rock', 'Fayetteville', 6006);

INSERT INTO TRUCKLOAD(ID, SOURCE, DESTINATION, CARRIERID)
VALUES (6, 'Little Rock', 'West Fork', 6006);