CREATE SEQUENCE Truckload_Seq START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 10000 CYCLE;
CREATE SEQUENCE Carrier_Seq START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 10000 CYCLE;




CREATE TABLE CARRIER(
    CARRIERID INTEGER PRIMARY KEY,
    NAME VARCHAR(16) NOT NULL
);


CREATE TABLE TRUCKLOAD(
    ID INTEGER PRIMARY KEY,
    SOURCE VARCHAR(16) NOT NULL,
    DESTINATION VARCHAR(16) NOT NULL,

    CARRIERID INTEGER,
    FOREIGN KEY (CARRIERID) REFERENCES CARRIER(CARRIERID)

);




CREATE TABLE USERS(
    username VARCHAR(50) NOT NULL primary key,
    password VARCHAR(255) NOT NULL,
    enabled bit not NULL
);