CREATE SEQUENCE Person_Seq
START WITH 1
INCREMENT BY 50
MINVALUE 1
MAXVALUE 10000
CYCLE;


CREATE TABLE PERSON(
  ID INTEGER PRIMARY KEY,
  FIRST_NAME VARCHAR(16) NOT NULL,
  LAST_NAME VARCHAR(16) NOT NULL
);
